"""
Comprehensive whitelist of legitimate domains from trusted organizations and companies.
This list includes major tech companies, financial institutions, government sites,
educational institutions, news outlets, and other well-known legitimate services.
"""

LEGITIMATE_DOMAINS = {
    # Tech Giants & Cloud Services
    'google.com', 'microsoft.com', 'apple.com', 'amazon.com', 'meta.com', 'facebook.com',
    'alphabet.com', 'aws.amazon.com', 'azure.microsoft.com', 'cloud.google.com',
    'icloud.com', 'live.com', 'msn.com', 'bing.com', 'google.co.uk', 'google.de',
    'google.fr', 'google.ca', 'google.in', 'google.jp', 'google.com.au', 'google.es',
    'google.it', 'google.br', 'google.mx', 'google.ru', 'google.nl', 'google.pl',
    'google.se', 'google.no', 'google.dk', 'google.fi', 'google.ch', 'google.at',
    'google.be', 'google.ie', 'google.pt', 'google.gr', 'google.cz', 'google.ro',
    'google.hu', 'google.tr', 'google.sg', 'google.my', 'google.th', 'google.id',
    'google.ph', 'google.vn', 'google.kr', 'google.hk', 'google.tw', 'google.cn',
    'google.co.za', 'google.ae', 'google.sa', 'google.eg', 'google.co.il', 'google.co.nz',
    'google.com.ar', 'google.cl', 'google.co', 'google.com.co', 've.google.com',
    'microsoftonline.com', 'login.microsoftonline.com', 'login.live.com', 'account.microsoft.com',
    'windowsazure.com', 'azurewebsites.net', 'azurefd.net', 'cloudapp.azure.com',
    'office.com', 'office365.com', 'sharepoint.com', 'onedrive.com', 'outlook.com',
    'visualstudio.com', 'dev.azure.com', 'github.com', 'github.io',
    'googleapis.com', 'gstatic.com', 'googleusercontent.com', 'googlevideo.com',
    'googletagmanager.com', 'googleadservices.com', 'googlesyndication.com',
    'doubleclick.net', 'ampproject.org', 'amp.dev', 'android.com', 'chromium.org',
    'apple.co', 'me.com', 'mac.com', 'itunes.apple.com', 'apps.apple.com',
    'appstore.com', 'cdn-apple.com', 'mzstatic.com', 'appleid.apple.com',
    'amazon.co.uk', 'amazon.de', 'amazon.fr', 'amazon.it', 'amazon.es',
    'amazon.ca', 'amazon.com.au', 'amazon.com.br', 'amazon.in', 'amazon.cn',
    'amazon.co.jp', 'amazon.com.mx', 'amazon.nl', 'amazon.se', 'amazon.sg',
    'amazonwebservices.com', 'aws.com', 'cloudfront.net', 'amazonaws.com',
    's3.amazonaws.com', 'ec2.amazonaws.com', 'elasticbeanstalk.com',
    
    # Social Media & Communication
    'twitter.com', 'x.com', 'instagram.com', 'linkedin.com', 'pinterest.com', 
    'snapchat.com', 'tiktok.com', 'whatsapp.com', 'telegram.org', 'discord.com',
    'reddit.com', 'tumblr.com', 'vimeo.com', 'youtube.com', 'youtu.be',
    'messenger.com', 'fb.com', 'fb.me', 'signal.org', 'line.me', 'wechat.com',
    'mastodon.social', 'threads.net', 'bluesky.social', 'bsky.app', 'bluesky.app',
    'twimg.com', 'fbcdn.net', 'cdninstagram.com', 'licdn.com', 'pinimg.com',
    'discordapp.com', 'discord.gg', 'tenor.com', 'giphy.com', 'imgur.com',
    'flickr.com', 'photobucket.com', 'dailymotion.com', 'vk.com', 'ok.ru',
    'weibo.com', 'qq.com', 'douyin.com', 'kuaishou.com', 'bilibili.com',
    'telegram.me', 't.me', 'viber.com', 'kakao.com', 'naver.com', 'band.us',
    
    # Developer Platforms & Open Source
    'github.com', 'gitlab.com', 'bitbucket.org', 'stackoverflow.com', 'stackexchange.com',
    'npmjs.com', 'pypi.org', 'packagist.org', 'nuget.org', 'maven.apache.org',
    'jetbrains.com', 'visualstudio.com', 'code.visualstudio.com', 'github.io',
    'readthedocs.org', 'readthedocs.io', 'codepen.io', 'jsfiddle.net', 'replit.com',
    'codesandbox.io', 'glitch.com', 'heroku.com', 'herokuapp.com', 'vercel.app',
    'vercel.com', 'netlify.app', 'netlify.com', 'railway.app', 'render.com',
    'fly.io', 'cloudflare.com', 'pages.dev', 'workers.dev', 'cloudflare.net',
    'sourceforge.net', 'launchpad.net', 'gnu.org', 'fsf.org', 'opensource.org',
    'gitpod.io', 'codespaces.dev', 'stackblitz.com', 'webcontainer.io',
    'crates.io', 'rubygems.org', 'hex.pm', 'pub.dev', 'cocoapods.org',
    'jsdelivr.net', 'unpkg.com', 'cdnjs.com', 'cdnjs.cloudflare.com',
    
    # Cloud & Enterprise Software
    'salesforce.com', 'force.com', 'visualforce.com', 'oracle.com', 'ibm.com',
    'sap.com', 'vmware.com', 'dell.com', 'hp.com', 'hpe.com', 'cisco.com',
    'atlassian.com', 'atlassian.net', 'jira.com', 'confluence.com', 'servicenow.com',
    'workday.com', 'zendesk.com', 'hubspot.com', 'mailchimp.com', 'intuit.com',
    'quickbooks.com', 'xero.com', 'freshworks.com', 'freshdesk.com', 'intercom.com',
    'segment.com', 'mixpanel.com', 'amplitude.com', 'datadog.com', 'datadoghq.com',
    'splunk.com', 'tableau.com', 'powerbi.microsoft.com', 'looker.com', 'grafana.com',
    'grafana.net', 'elastic.co', 'elasticsearch.com', 'mongodb.com', 'redis.io',
    'redislabs.com', 'postgresql.org', 'mysql.com', 'mariadb.org', 'sqlite.org',
    'neo4j.com', 'couchbase.com', 'influxdata.com', 'timescale.com',
    
    # Collaboration & Productivity Tools
    'slack.com', 'slack-edge.com', 'zoom.us', 'teams.microsoft.com', 'webex.com',
    'gotomeeting.com', 'meet.google.com', 'hangouts.google.com', 'skype.com',
    'whereby.com', 'jitsi.org', 'meet.jit.si', 'bluejeans.com', 'ringcentral.com',
    'notion.so', 'notion.site', 'asana.com', 'trello.com', 'monday.com',
    'airtable.com', 'clickup.com', 'basecamp.com', 'wrike.com', 'smartsheet.com',
    'miro.com', 'mural.co', 'figma.com', 'figjam.com', 'sketch.com', 'invisionapp.com',
    'dropbox.com', 'box.com', 'onedrive.live.com', 'drive.google.com', 'sync.com',
    'mega.nz', 'mega.io', 'pcloud.com', 'tresorit.com', 'egnyte.com', 'sharefile.com',
    'evernote.com', 'onenote.com', 'simplenote.com', 'bear.app', 'roamresearch.com',
    'obsidian.md', 'logseq.com', 'craft.do', 'coda.io', 'quip.com',
    
    # E-commerce & Retail
    'paypal.com', 'paypal.me', 'stripe.com', 'square.com', 'shopify.com',
    'ebay.com', 'ebay.co.uk', 'ebay.de', 'ebay.fr', 'ebay.it', 'ebay.es',
    'ebay.ca', 'ebay.com.au', 'ebay.in', 'ebaystatic.com', 'ebayimg.com',
    'etsy.com', 'etsystatic.com', 'walmart.com', 'target.com', 'bestbuy.com',
    'aliexpress.com', 'alibaba.com', 'alicdn.com', 'taobao.com', 'tmall.com',
    'jd.com', '1688.com', 'costco.com', 'samsclub.com', 'homedepot.com',
    'lowes.com', 'ikea.com', 'wayfair.com', 'overstock.com', 'newegg.com',
    'bhphotovideo.com', 'adorama.com', 'rakuten.com', 'mercari.com', 'poshmark.com',
    'depop.com', 'grailed.com', 'stockx.com', 'goat.com', 'reverb.com',
    'discogs.com', 'bandcamp.com', 'redbubble.com', 'teepublic.com', 'zazzle.com',
    
    # Payment & Financial Tech
    'venmo.com', 'cashapp.com', 'cash.app', 'zelle.com', 'payoneer.com',
    'wise.com', 'transferwise.com', 'revolut.com', 'n26.com', 'monzo.com',
    'chime.com', 'plaid.com', 'braintreepayments.com', 'braintreegateway.com',
    'adyen.com', 'checkout.com', 'klarna.com', 'afterpay.com', 'affirm.com',
    'sezzle.com', 'quadpay.com', 'splitit.com', 'paypal-credit.com',
    
    # Streaming & Entertainment
    'netflix.com', 'nflxvideo.net', 'nflxext.com', 'nflximg.net', 'hulu.com',
    'disneyplus.com', 'disney.com', 'disneynow.com', 'hbomax.com', 'max.com',
    'primevideo.com', 'amazonvideo.com', 'spotify.com', 'scdn.co', 'soundcloud.com',
    'pandora.com', 'twitch.tv', 'twitchcdn.net', 'kick.com', 'steam.com',
    'steampowered.com', 'steamcommunity.com', 'steamstatic.com', 'deezer.com',
    'tidal.com', 'applemusic.com', 'music.apple.com', 'music.youtube.com',
    'music.amazon.com', 'crunchyroll.com', 'funimation.com', 'vrv.co',
    'paramountplus.com', 'peacocktv.com', 'showtime.com', 'starz.com', 'sling.com',
    'vudu.com', 'fandango.com', 'imdb.com', 'imdbcdn.com', 'rottentomatoes.com',
    'metacritic.com', 'letterboxd.com', 'myanimelist.net', 'anilist.co',
    
    # Education & Learning
    'wikipedia.org', 'wikimedia.org', 'wikidata.org', 'mediawiki.org', 'wikihow.com',
    'coursera.org', 'udemy.com', 'udacity.com', 'edx.org', 'khanacademy.org',
    'skillshare.com', 'pluralsight.com', 'linkedin-learning.com', 'lynda.com',
    'masterclass.com', 'brilliant.org', 'codecademy.com', 'freecodecamp.org',
    'w3schools.com', 'mdn.mozilla.org', 'developer.mozilla.org', 'mozilla.org',
    'geeksforgeeks.org', 'tutorialspoint.com', 'javatpoint.com', 'programiz.com',
    'mit.edu', 'stanford.edu', 'harvard.edu', 'yale.edu', 'princeton.edu',
    'columbia.edu', 'berkeley.edu', 'caltech.edu', 'uchicago.edu', 'upenn.edu',
    'cornell.edu', 'duke.edu', 'northwestern.edu', 'jhu.edu', 'dartmouth.edu',
    'brown.edu', 'vanderbilt.edu', 'rice.edu', 'wustl.edu', 'georgetown.edu',
    'oxford.ac.uk', 'cambridge.ac.uk', 'imperial.ac.uk', 'ucl.ac.uk', 'ed.ac.uk',
    'kcl.ac.uk', 'manchester.ac.uk', 'warwick.ac.uk', 'bristol.ac.uk', 'lse.ac.uk',
    'cambridge.org', 'oup.com', 'springer.com', 'springerlink.com', 'nature.com',
    'sciencedirect.com', 'jstor.org', 'researchgate.net', 'academia.edu',
    'scholar.google.com', 'arxiv.org', 'biorxiv.org', 'medrxiv.org', 'ssrn.com',
    'pubmed.ncbi.nlm.nih.gov', 'nih.gov', 'ncbi.nlm.nih.gov', 'nejm.org',
    'medium.com', 'substack.com', 'dev.to', 'hashnode.com', 'hackernoon.com',
    'towardsdatascience.com', 'analyticsvidhya.com', 'kdnuggets.com',
    
    # News & Media
    'nytimes.com', 'washingtonpost.com', 'theguardian.com', 'bbc.com', 'bbc.co.uk',
    'cnn.com', 'foxnews.com', 'msnbc.com', 'nbcnews.com', 'cbsnews.com',
    'abcnews.go.com', 'reuters.com', 'apnews.com', 'bloomberg.com', 'wsj.com',
    'ft.com', 'forbes.com', 'businessinsider.com', 'economist.com', 'time.com',
    'newsweek.com', 'usatoday.com', 'latimes.com', 'chicagotribune.com',
    'sfchronicle.com', 'bostonglobe.com', 'nypost.com', 'nydailynews.com',
    'techcrunch.com', 'wired.com', 'theverge.com', 'engadget.com', 'arstechnica.com',
    'cnet.com', 'zdnet.com', 'pcmag.com', 'tomshardware.com', 'anandtech.com',
    'vice.com', 'vox.com', 'buzzfeed.com', 'buzzfeednews.com', 'huffpost.com',
    'politico.com', 'thehill.com', 'axios.com', 'propublica.org', 'apnews.com',
    'aljazeera.com', 'dw.com', 'france24.com', 'euronews.com', 'scmp.com',
    'npr.org', 'pbs.org', 'cbslocal.com', 'abclocal.go.com', 'nbclocal.com',
    
    # Software & Design Tools
    'adobe.com', 'adobelogin.com', 'adobecc.com', 'adobecreativecloud.com',
    'autodesk.com', 'figma.com', 'canva.com', 'sketch.com', 'invisionapp.com',
    'zeplin.io', 'framer.com', 'webflow.com', 'squarespace.com', 'wix.com',
    'wordpress.com', 'wordpress.org', 'wp.com', 'wp.org', 'wpengine.com',
    'tumblr.com', 'blogger.com', 'blogspot.com', 'ghost.org', 'ghost.io',
    'drupal.org', 'joomla.org', 'contentful.com', 'sanity.io', 'strapi.io',
    'prismic.io', 'buttercms.com', 'storyblok.com', 'directus.io',
    'unity.com', 'unity3d.com', 'unrealengine.com', 'godotengine.org',
    'blender.org', 'gimp.org', 'inkscape.org', 'krita.org', 'affinity.serif.com',
    'corel.com', 'sketchup.com', 'trimble.com', 'rhino3d.com', 'maxon.net',
    
    # DevOps & Infrastructure
    'docker.com', 'docker.io', 'kubernetes.io', 'k8s.io', 'terraform.io',
    'ansible.com', 'puppet.com', 'chef.io', 'jenkins.io', 'travis-ci.org',
    'travis-ci.com', 'circleci.com', 'gitlab.com', 'actions.github.com',
    'buildkite.com', 'teamcity.jetbrains.com', 'bamboo.atlassian.com',
    'octopus.com', 'pagerduty.com', 'opsgenie.com', 'statuspage.io',
    'pingdom.com', 'newrelic.com', 'sentry.io', 'rollbar.com', 'bugsnag.com',
    'loggly.com', 'papertrail.com', 'sumologic.com', 'prometheus.io',
    'grafana.com', 'jaegertracing.io', 'opentelemetry.io', 'istio.io',
    
    # Security & Privacy
    'okta.com', 'auth0.com', 'duo.com', 'onelogin.com', 'ping.com',
    'pingidentity.com', 'jumpcloud.com', 'lastpass.com', '1password.com',
    'bitwarden.com', 'dashlane.com', 'keepass.info', 'keeper.io',
    'nordvpn.com', 'expressvpn.com', 'surfshark.com', 'protonvpn.com',
    'proton.me', 'protonmail.com', 'privatevpn.com', 'purevpn.com',
    'malwarebytes.com', 'norton.com', 'mcafee.com', 'kaspersky.com',
    'kaspersky.co.uk', 'bitdefender.com', 'avast.com', 'avg.com',
    'sophos.com', 'crowdstrike.com', 'fortinet.com', 'paloaltonetworks.com',
    'cloudflare.com', 'akamai.com', 'fastly.com', 'fastly.net', 'imperva.com',
    'f5.com', 'checkpoint.com', 'trendmicro.com', 'eset.com', 'webroot.com',
    
    # Domain & Hosting
    'namecheap.com', 'godaddy.com', 'name.com', 'gandi.net', 'hover.com',
    'dynadot.com', 'enom.com', 'networksolutions.com', 'register.com',
    'bluehost.com', 'hostgator.com', 'dreamhost.com', 'siteground.com',
    'inmotion.com', 'a2hosting.com', 'wpengine.com', 'kinsta.com',
    'cloudways.com', 'digitalocean.com', 'linode.com', 'vultr.com',
    'ovh.com', 'ovh.net', 'hetzner.com', 'hetzner.de', 'contabo.com',
    'rackspace.com', 'liquidweb.com', 'hostinger.com', 'ionos.com',
    
    # Email & Communication
    'gmail.com', 'googlemail.com', 'outlook.com', 'hotmail.com', 'yahoo.com',
    'yahoo.co.uk', 'yahoo.co.jp', 'ymail.com', 'aol.com', 'aim.com',
    'protonmail.com', 'proton.me', 'tutanota.com', 'mailbox.org', 'posteo.de',
    'zoho.com', 'fastmail.com', 'mail.com', 'gmx.com', 'gmx.net', 'gmx.de',
    'yandex.com', 'yandex.ru', 'icloud.com', 'me.com', 'mac.com',
    'office.com', 'office365.com', 'exchange.microsoft.com', 'mail.google.com',
    'docs.google.com', 'sheets.google.com', 'slides.google.com', 'forms.google.com',
    'calendar.google.com', 'keep.google.com', 'sites.google.com',
    'sendgrid.com', 'sendgrid.net', 'mailgun.com', 'mailjet.com', 'sendinblue.com',
    'constantcontact.com', 'campaignmonitor.com', 'aweber.com', 'getresponse.com',
    
    # Gaming & Entertainment
    'epicgames.com', 'unrealengine.com', 'fortnite.com', 'riotgames.com',
    'leagueoflegends.com', 'valorant.com', 'blizzard.com', 'battle.net',
    'battlenet.com', 'ea.com', 'origin.com', 'ubisoft.com', 'ubi.com',
    'rockstargames.com', 'gtav.com', 'reddead.com', 'square-enix.com',
    'squareenix.com', 'bandainamco.com', 'bandainamcoent.com', 'sega.com',
    'nintendo.com', 'nintendo.co.jp', 'nintendo.net', 'playstation.com',
    'sony.com', 'sonyentertainmentnetwork.com', 'xbox.com', 'microsoft.com',
    'minecraft.net', 'mojang.com', 'roblox.com', 'rbxcdn.com', 'unity.com',
    'itch.io', 'gog.com', 'gog-statics.com', 'humblebundle.com', 'humble.com',
    'greenmangaming.com', 'fanatical.com', 'gamersgate.com', 'bundlestars.com',
    'discord.gg', 'discordapp.com', 'teamspeak.com', 'ventrilo.com', 'mumble.info',
    'overwolf.com', 'curseforge.com', 'modrinth.com', 'nexusmods.com',
    
    # Financial Services & Banking
    'chase.com', 'jpmorganchase.com', 'bankofamerica.com', 'wellsfargo.com',
    'citibank.com', 'citi.com', 'usbank.com', 'pnc.com', 'truist.com',
    'tdbank.com', 'bbt.com', 'regions.com', 'fifththird.com', 'keybank.com',
    'americanexpress.com', 'amex.com', 'capitalone.com', 'discover.com',
    'synchrony.com', 'barclays.com', 'barclays.co.uk', 'hsbc.com', 'hsbc.co.uk',
    'fidelity.com', 'schwab.com', 'tdameritrade.com', 'etrade.com',
    'interactivebrokers.com', 'thinkorswim.com', 'tastytrade.com',
    'robinhood.com', 'webull.com', 'coinbase.com', 'coinbase.pro', 'pro.coinbase.com',
    'binance.com', 'binance.us', 'kraken.com', 'gemini.com', 'blockchain.com',
    'crypto.com', 'bitfinex.com', 'bitstamp.net', 'kucoin.com', 'okx.com',
    'vanguard.com', 'blackrock.com', 'statestreet.com', 'morganstanley.com',
    'goldmansachs.com', 'jpmorganonline.com', 'merrilledge.com', 'merrilllynch.com',
    'ally.com', 'marcus.com', 'sofi.com', 'betterment.com', 'wealthfront.com',
    
    # Government & Official Organizations
    'gov.uk', 'gov.ie', 'gov.au', 'gov.ca', 'gov.nz', 'gov.sg', 'gov.in',
    'gov.za', 'gov.il', 'gov.br', 'gov.mx', 'gov.ar', 'gov.cl', 'gov.co',
    'usa.gov', 'whitehouse.gov', 'state.gov', 'defense.gov', 'justice.gov',
    'irs.gov', 'ssa.gov', 'cdc.gov', 'fda.gov', 'epa.gov', 'nih.gov',
    'nasa.gov', 'noaa.gov', 'weather.gov', 'usgs.gov', 'nps.gov',
    'sec.gov', 'ftc.gov', 'fcc.gov', 'fema.gov', 'dhs.gov', 'tsa.gov',
    'treasury.gov', 'federalreserve.gov', 'usda.gov', 'ed.gov', 'hhs.gov',
    'va.gov', 'doc.gov', 'energy.gov', 'dot.gov', 'transportation.gov',
    'europa.eu', 'ec.europa.eu', 'un.org', 'who.int', 'unicef.org',
    'unesco.org', 'worldbank.org', 'imf.org', 'oecd.org', 'wto.org',
    'nato.int', 'icrc.org', 'redcross.org', 'ifrc.org', 'redcrossblood.org',
    'savethechildren.org', 'oxfam.org', 'msf.org', 'doctorswithoutborders.org',
    'amnesty.org', 'hrw.org', 'greenpeace.org', 'wwf.org', 'nature.org',
    'mozilla.org', 'apache.org', 'linux.org', 'linuxfoundation.org',
    'debian.org', 'ubuntu.com', 'canonical.com', 'redhat.com', 'fedoraproject.org',
    'kernel.org', 'python.org', 'nodejs.org', 'rust-lang.org', 'golang.org',
    'php.net', 'ruby-lang.org', 'swift.org', 'kotlinlang.org', 'scala-lang.org',
    
    # Travel & Transportation
    'booking.com', 'priceline.com', 'hotels.com', 'expedia.com', 'hotwire.com',
    'kayak.com', 'trivago.com', 'tripadvisor.com', 'airbnb.com', 'vrbo.com',
    'homeaway.com', 'agoda.com', 'hostelworld.com', 'skyscanner.com', 'orbitz.com',
    'travelocity.com', 'cheaptickets.com', 'momondo.com', 'kiwi.com',
    'uber.com', 'lyft.com', 'doordash.com', 'grubhub.com', 'ubereats.com',
    'postmates.com', 'instacart.com', 'shipt.com', 'gopuff.com', 'getir.com',
    'deliveroo.com', 'deliveroo.co.uk', 'justeat.com', 'just-eat.com',
    'delta.com', 'united.com', 'american.com', 'aa.com', 'southwest.com',
    'southwestair.com', 'jetblue.com', 'alaskaair.com', 'spirit.com',
    'frontier.com', 'allegiantair.com', 'britishairways.com', 'ba.com',
    'lufthansa.com', 'airfrance.com', 'klm.com', 'emirates.com', 'qantas.com',
    'ana.co.jp', 'jal.co.jp', 'cathaypacific.com', 'singaporeair.com',
    'marriott.com', 'hilton.com', 'hyatt.com', 'ihg.com', 'choicehotels.com',
    'bestwestern.com', 'wyndham.com', 'radisson.com', 'accor.com', 'mgmresorts.com',
    'caesars.com', 'subway.com', 'hertz.com', 'enterprise.com', 'avis.com',
    'budget.com', 'nationalcar.com', 'alamo.com', 'thrifty.com', 'dollar.com',
    'amtrak.com', 'via.com', 'eurostar.com', 'renfe.com', 'sncf.com',
    
    # Health & Medical
    'mayoclinic.org', 'clevelandclinic.org', 'hopkinsmedicine.org', 'webmd.com',
    'healthline.com', 'medlineplus.gov', 'nih.gov', 'cdc.gov', 'fda.gov',
    'who.int', 'drugs.com', 'rxlist.com', 'medscape.com', 'uptodate.com',
    'cvs.com', 'cvspharmacy.com', 'walgreens.com', 'riteaid.com', 'walmart.com',
    'kaiser.com', 'kaiserpermanente.org', 'kp.org', 'bcbs.com', 'bcbsm.com',
    'unitedhealthcare.com', 'uhc.com', 'aetna.com', 'cigna.com', 'humana.com',
    'anthem.com', 'wellcare.com', 'centene.com', 'molina.com', 'healthnet.com',
    '23andme.com', 'ancestry.com', 'myheritage.com', 'familysearch.org',
    
    # Telecommunications
    'att.com', 'verizon.com', 'vzw.com', 'verizonwireless.com', 't-mobile.com',
    'sprint.com', 'xfinity.com', 'comcast.com', 'comcast.net', 'spectrum.com',
    'cox.com', 'centurylink.com', 'frontier.com', 'windstream.com', 'optimum.com',
    'vodafone.com', 'vodafone.co.uk', 'orange.com', 'orange.fr', 'telefonica.com',
    'bt.com', 'sky.com', 'virginmedia.com', 'o2.com', 'o2.co.uk', 'ee.co.uk',
    'three.co.uk', 'telstra.com.au', 'optus.com.au', 'rogers.com', 'bell.ca',
    'telus.com', 'att.net', 'bellsouth.net', 'sbcglobal.net', 'charter.net',
    
    # Additional Major Brands
    'coca-cola.com', 'cocacola.com', 'pepsi.com', 'pepsico.com', 'starbucks.com',
    'mcdonalds.com', 'burgerking.com', 'tacobell.com', 'pizzahut.com', 'kfc.com',
    'chipotle.com', 'dominos.com', 'papajohns.com', 'subway.com', 'wendys.com',
    'nike.com', 'adidas.com', 'puma.com', 'underarmour.com', 'reebok.com',
    'newbalance.com', 'vans.com', 'converse.com', 'skechers.com', 'asics.com',
    'gap.com', 'oldnavy.com', 'bananarepublic.com', 'athleta.com', 'zara.com',
    'hm.com', 'uniqlo.com', 'forever21.com', 'urbanoutfitters.com', 'ae.com',
    'abercrombie.com', 'hollister.com', 'victoriassecret.com', 'anthropologie.com',
    'macys.com', 'nordstrom.com', 'bloomingdales.com', 'saksfifthavenue.com',
    'neimanmarcus.com', 'dillards.com', 'kohls.com', 'jcpenney.com', 'sears.com',
    'toyota.com', 'ford.com', 'gm.com', 'chevrolet.com', 'honda.com', 'nissan.com',
    'bmw.com', 'bmwusa.com', 'mercedes-benz.com', 'mbusa.com', 'audi.com',
    'volkswagen.com', 'vw.com', 'tesla.com', 'porsche.com', 'mazda.com',
    'subaru.com', 'hyundai.com', 'kia.com', 'lexus.com', 'infiniti.com',
    'acura.com', 'cadillac.com', 'lincoln.com', 'jeep.com', 'ram.com',
    
    # Additional Tech & Services
    'twilio.com', 'sendgrid.com', 'mailchimp.com', 'constantcontact.com',
    'convertkit.com', 'activecampaign.com', 'hubspot.com', 'marketo.com',
    'pardot.com', 'eloqua.com', 'salesforce.com', 'force.com',
    'zoom.us', 'zoomgov.com', 'webex.com', 'gotomeeting.com', 'goto.com',
    'logmein.com', 'teamviewer.com', 'anydesk.com', 'citrix.com',
    'zapier.com', 'ifttt.com', 'make.com', 'integromat.com', 'n8n.io',
    'airtable.com', 'notion.so', 'coda.io', 'clickup.com', 'asana.com',
    'monday.com', 'smartsheet.com', 'wrike.com', 'basecamp.com', 'jira.com',
    
    # CDN & Infrastructure Domains
    'cloudfront.net', 'azureedge.net', 'akamaized.net', 'akamaihd.net',
    'fastly.net', 'fastly.com', 'edgecastcdn.net', 'stackpathdns.com',
    'kxcdn.com', 'maxcdn.com', 'jsdelivr.net', 'unpkg.com', 'cdnjs.com',
    'bootstrapcdn.com', 'fontawesome.com', 'fonts.googleapis.com',
    'fonts.gstatic.com', 'ajax.googleapis.com', 'code.jquery.com',
    
    # Additional Educational & Research
    'mit.edu', 'stanford.edu', 'harvard.edu', 'yale.edu', 'princeton.edu',
    'caltech.edu', 'columbia.edu', 'uchicago.edu', 'upenn.edu', 'cornell.edu',
    'duke.edu', 'northwestern.edu', 'jhu.edu', 'dartmouth.edu', 'brown.edu',
    'ucsd.edu', 'ucla.edu', 'usc.edu', 'umich.edu', 'wisc.edu', 'uiuc.edu',
    'utexas.edu', 'washington.edu', 'uw.edu', 'gatech.edu', 'cmu.edu',
    'nyu.edu', 'bu.edu', 'neu.edu', 'tufts.edu', 'rochester.edu',
}

# URL shortener domains - exact matches only
URL_SHORTENERS = {
    'bit.ly', 'tinyurl.com', 'goo.gl', 't.co', 'ow.ly', 'is.gd',
    'buff.ly', 'adf.ly', 'short.link', 'tiny.cc', 'rb.gy', 'v.gd',
    'clck.ru', 'shorturl.at', 'cutt.ly', 'tinycc.com', 'bl.ink',
    'lnkd.in', 'ift.tt', 'soo.gd', 'surl.li', 'shorturl.com',
    's2r.co', 'clk.sh', 'chilp.it', 'x.co', 'prettylinkpro.com',
    'scrnch.me', 'filoops.info', 'virl.com', 'PrettyLink.com',
    'miniurl.com', 'su.pr', 'tweez.me', 'v.ht', 'trib.al',
    'zee.gl', '1url.com', 'b2l.me', 'lnk.bio', 'linktr.ee',
    'bio.link', 'link.bio', 'beacons.ai', 'hoo.be', 'carrd.co',
}
